config/routes.rb
RightjsNginxUploader::Application.routes.draw do

  root :to => 'uploads#new'
  
  
  resources :uploads

end

app/models/upload.rb
class Upload < ActiveRecord::Base

  has_attached_file :file,
    :url => "/system/files/:id/:basename_:style.:extension",
    :path => ":rails_root/public/system/files/:id/:basename_:style.:extension"
    #, :styles => {:icon => "60x60>", :thumb => "120x120>", :large => "240x240>"}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  # GET /uploads
  # GET /uploads.xml
  def index
    @uploads = Upload.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @uploads }
    end
  end

  # GET /uploads/1
  # GET /uploads/1.xml
  def show
    @upload = Upload.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @upload }
    end
  end

  # GET /uploads/new
  # GET /uploads/new.xml
  def new
    @upload = Upload.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @upload }
    end
  end

  # GET /uploads/1/edit
  def edit
    @upload = Upload.find(params[:id])
  end

  # POST /uploads
  # POST /uploads.xml
  def create
    @upload = Upload.new(params[:upload])

    respond_to do |format|
      if @upload.save
        flash[:notice] = 'upload was successfully created.'
        format.html { redirect_to(@upload) }
        format.js   { render rjs.insert_and_care(@upload) }
      else
        format.html { render :action => "new" }
        format.js   { render rjs.replace_form_for(@upload) }
      end
    end
  end

  # PUT /uploads/1
  # PUT /uploads/1.xml
  def update
    @upload = Upload.find(params[:id])

    respond_to do |format|
      if @upload.update_attributes(params[:upload])
        format.html { redirect_to(@upload, :notice => 'Upload was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @upload.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /uploads/1
  # DELETE /uploads/1.xml
  def destroy
    @upload = Upload.find(params[:id])
    @upload.destroy

    respond_to do |format|
      format.html { redirect_to(uploads_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RightJS Nginx Uploader Test</title>
    <%= stylesheet_link_tag 'screen' %>
    <%= javascript_include_tag :defaults, 'uploader' %>
    <%= csrf_meta_tag %>
    <%= yield :js %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/iframed.html.erb
<html>
  <head>
    <script type='text/javascript'>
      with (window.parent) {
        <%= yield %>
      }
    </script>
  </head>
</html>

app/views/uploads/_form.html.erb
<%= form_for @upload, :url => '/uploads.js', :html => {:multipart => true } do |f| %>
  <% if @upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@upload.errors.count, "error") %> prohibited this upload from being saved:</h2>
      <ul>
      <% @upload.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :file %><br>
    <%= f.file_field :file %>
    <button id='upload'>Upload</button>
  </div>
  <div class="preview"></div>
  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/uploads/_upload.html.erb
<p id="notice"><%= notice %></p>

<img src='<%= upload.file.url %>' />

<p>
  <b>File size:</b>
  <%= upload.file_file_size %>
</p>

<p>
  <b>Content type:</b>
  <%= upload.file_content_type %>
</p>


<%= link_to 'Edit', edit_upload_path(upload) %> |
<%= link_to 'Back', uploads_path %>

app/views/uploads/edit.html.erb
<h1>Editing upload</h1>

<%= render 'form' %>

<%= link_to 'Show', @upload %> |
<%= link_to 'Back', uploads_path %>

app/views/uploads/index.html.erb
<h1>Listing uploads</h1>

<table>
  <tr>
    <th>File file name</th>
    <th>File file size</th>
    <th>File content type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @uploads.each do |upload| %>
  <tr>
    <td><%= upload.file_file_name %></td>
    <td><%= upload.file_file_size %></td>
    <td><%= upload.file_content_type %></td>
    <td><%= link_to 'Show', upload %></td>
    <td><%= link_to 'Edit', edit_upload_path(upload) %></td>
    <td><%= link_to 'Destroy', upload, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Upload', new_upload_path %>

app/views/uploads/new.html.erb
<h1>New upload</h1>

<%= render 'form' %>

<%= link_to 'Back', uploads_path %>

app/views/uploads/show.html.erb
<p id="notice"><%= notice %></p>

<img src='<%= @upload.file.url %>' />

<p>
  <b>File size:</b>
  <%= @upload.file_file_size %>
</p>

<p>
  <b>Content type:</b>
  <%= @upload.file_content_type %>
</p>


<%= link_to 'Edit', edit_upload_path(@upload) %> |
<%= link_to 'Back', uploads_path %>